name: meli_cyber_ai_clean
channels:
  - defaults
dependencies:
  - python=3.11.13
  - pandas
  - seaborn
  - joblib
  - scikit-learn
  - langchain
  - uvicorn
  - fastapi
  - pip:
    - langgraph
    - langchain-openai
    - langchain_google_genai
  